/* Copyright (c) 2026 multiarch-scala contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Shared cross-platform resource-access mechanism.
 *
 * `PlatformResources` provides a uniform way to read classpath-style resources on the JVM,
 * Scala.js, and Scala Native. The per-platform implementation lives in `PlatformResourcesImpl`,
 * which has separate sources under `src/main/scalajvm`, `src/main/scalajs`, and
 * `src/main/scalanative`.
 *
 *   - JVM / Native delegate to `Class.getResourceAsStream` (the classpath).
 *   - Scala.js, which has no classpath, consults a build-time-embedded map first (generated by
 *     the plugin's `EmbeddedResourcesGen`) and falls back to a Node `fs` lookup for development.
 *
 * The API deliberately uses plain Scala types (`Option`, `Array[Byte]`, `String`,
 * `java.io.InputStream`) so the module stays self-contained with no third-party dependency.
 */
package multiarch
package resources

import java.io.InputStream

object PlatformResources {

  /** Open a resource as an `InputStream`, or `None` if it cannot be found.
    *
    * The path is resolved the same way as `Class.getResourceAsStream`: a leading `/` makes it absolute (relative to the classpath root); otherwise it is resolved relative to `cls`'s package. On
    * Scala.js the path is normalized to a classpath-absolute key before the embedded map / fs fallback are consulted.
    *
    * @param cls
    *   class whose classloader / package is used to resolve the resource
    * @param path
    *   resource path, e.g. "/data/table.csv"
    */
  def getResourceAsStream(cls: Class[?], path: String): Option[InputStream] =
    PlatformResourcesImpl.getResourceAsStream(cls, path)

  /** Read a resource fully into a byte array, or `None` if it cannot be found. */
  def getResourceBytes(cls: Class[?], path: String): Option[Array[Byte]] =
    getResourceAsStream(cls, path).map { in =>
      try readAllBytes(in)
      finally in.close()
    }

  /** Read a resource fully as a UTF-8 `String`, or `None` if it cannot be found. */
  def getResourceAsString(cls: Class[?], path: String): Option[String] =
    getResourceBytes(cls, path).map(bytes => new String(bytes, "UTF-8"))

  /** Whether a resource exists and can be opened. */
  def resourceExists(cls: Class[?], path: String): Boolean =
    getResourceAsStream(cls, path) match {
      case Some(in) =>
        in.close()
        true
      case None =>
        false
    }

  // java.io.InputStream#readAllBytes is JDK 9+ and unavailable on Scala.js / Native, so read by
  // hand into a growing buffer for portability across all three platforms.
  private def readAllBytes(in: InputStream): Array[Byte] = {
    val buffer = new Array[Byte](8192)
    var out    = new Array[Byte](0)
    var read   = in.read(buffer)
    while (read >= 0) {
      if (read > 0) {
        val grown = new Array[Byte](out.length + read)
        System.arraycopy(out, 0, grown, 0, out.length)
        System.arraycopy(buffer, 0, grown, out.length, read)
        out = grown
      }
      read = in.read(buffer)
    }
    out
  }
}
