/* Copyright (c) 2026 multiarch-scala contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Build-time generator for the non-JVM halves of the shared service-provider lookup.
 *
 * `java.util.ServiceLoader` does not exist in the Scala.js javalib at all, and Scala Native's is a
 * link-time intrinsic whose `load` only accepts a literal `classOf` — so neither platform can serve a
 * `Class`-taking wrapper. Both instead turn the project's `META-INF/services/<service>` descriptors
 * into REGISTRATION CODE: for every provider line this generator emits
 *
 * {{{ PlatformServiceLoader.register(classOf[<service>], new <provider>()) }}}
 *
 * inside a self-registering object. Two consequences worth stating, because they are the reason the
 * generator emits code rather than a string table:
 *
 *   - every service and provider name becomes a SOURCE-LEVEL reference, so a descriptor naming a
 *     class that was renamed, dropped or never ported fails the COMPILE, loudly — where the JVM's own
 *     answer is a silently empty iterator;
 *   - nothing is reflected on at run time, which Scala.js could not do anyway.
 *
 * Sibling of `EmbeddedResourcesGen`, which embeds resource BYTES; this one embeds CODE, so it has no
 * constant-pool chunking to worry about. */
package multiarch.sbt

import sbt._

import java.io.File
import java.nio.file.Files

object ServiceProvidersGen {

  /** Reads `<resourceDir>/META-INF/services` and writes a self-registering Scala object into `outFile`.
    *
    * @param resourceDir
    *   a resource root (e.g. `src/main/resources`) whose `META-INF/services` directory is read
    * @param outFile
    *   target Scala source file (typically under `sourceManaged`)
    * @param objectName
    *   fully-qualified name of the generated object, e.g. "my.lib.GeneratedServiceProviders"
    * @param log
    *   sbt logger
    * @return
    *   the generated file (so it can be returned from a `sourceGenerators` task)
    */
  def generate(resourceDir: File, outFile: File, objectName: String, log: sbt.util.Logger): File = {
    val descriptors       = ServiceDescriptors.read(resourceDir)
    val (pkg, simpleName) = splitName(objectName)

    val sb = new StringBuilder

    sb.append("/* Copyright (c) 2026 multiarch-scala contributors\n")
    sb.append(" * SPDX-License-Identifier: Apache-2.0\n")
    sb.append(" *\n")
    sb.append(" * GENERATED by multiarch.sbt.ServiceProvidersGen — do not edit by hand.\n")
    sb.append(" * Registers the providers declared in META-INF/services for the platforms that\n")
    sb.append(" * cannot discover them through java.util.ServiceLoader (Scala.js, Scala Native). */\n")
    if (pkg.nonEmpty) {
      sb.append("package ").append(pkg).append("\n\n")
    }
    sb.append("import multiarch.serviceloader.PlatformServiceLoader\n\n")
    sb.append("object ").append(simpleName).append(" {\n\n")

    if (descriptors.isEmpty) {
      sb.append("  // No META-INF/services descriptors were found under the configured resource directory.\n")
    }

    descriptors.foreach { case (service, providers) =>
      sb.append("  // ").append(ServiceDescriptors.ServicesPath).append("/").append(service).append("\n")
      if (providers.isEmpty) {
        sb.append("  // (no provider lines)\n")
      }
      providers.foreach { provider =>
        sb.append("  PlatformServiceLoader.register(classOf[").append(scalaName(service)).append("], new ").append(scalaName(provider)).append("())\n")
      }
      sb.append("\n")
    }

    sb.append("}\n")

    Files.createDirectories(outFile.toPath.getParent)
    IO.write(outFile, sb.toString)
    val total = descriptors.map(_._2.size).sum
    log.info(
      s"[multiarch-serviceloader] registered $total provider(s) for ${descriptors.size} service(s) " +
        s"into ${outFile.getName} ($objectName)"
    )
    outFile
  }

  // A binary name spells a nested class with '$', which Scala source cannot; `Outer.Inner` is how
  // Scala names the very same class. Top-level names contain no '$' in practice, so this is a
  // translation rather than a guess — and where it is wrong, the emitted `classOf[...]` does not
  // resolve and the JS build fails, which is the failure mode this generator exists to produce.
  private def scalaName(binaryName: String): String =
    binaryName.replace('$', '.')

  private def splitName(fqcn: String): (String, String) = {
    val idx = fqcn.lastIndexOf('.')
    if (idx < 0) ("", fqcn)
    else (fqcn.substring(0, idx), fqcn.substring(idx + 1))
  }
}
